ALTER TABLE public.linhas
  ADD COLUMN IF NOT EXISTS antec_t1 integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS prest_t1 integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS antec_t2 integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS prest_t2 integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS antec_t3 integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS prest_t3 integer NOT NULL DEFAULT 0;